"""Add upload_job table

Revision ID: 2fd3f2232673
Revises: c0044e099897
Create Date: 2025-10-20 16:26:49.859032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd3f2232673'
down_revision: Union[str, None] = 'c0044e099897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_jobs',
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='소속 회사'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='업로드한 사용자'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='원본 파일명'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='저장된 파일명'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='파일 크기(bytes)'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='파일 타입(csv/xlsx)'),
    sa.Column('encoding', sa.String(length=20), nullable=True, comment='파일 인코딩(utf-8/cp949)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='상태(pending/processing/completed/failed)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지'),
    sa.Column('total_rows', sa.Integer(), nullable=True, comment='총 행 수'),
    sa.Column('total_columns', sa.Integer(), nullable=True, comment='총 컬럼 수'),
    sa.Column('null_count', sa.Integer(), nullable=True, comment='결측치 개수'),
    sa.Column('duplicate_count', sa.Integer(), nullable=True, comment='중복 행 개수'),
    sa.Column('profile_data', sa.Text(), nullable=True, comment='프로파일 데이터(JSON)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_jobs_id'), 'upload_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_tenant_id'), 'upload_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_user_id'), 'upload_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_jobs_user_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_tenant_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_id'), table_name='upload_jobs')
    op.drop_table('upload_jobs')
    # ### end Alembic commands ###
